### ISSUE TITLE
Place LGPL header with Author name and email

### ISSUE THREAD

**Issue by kuldeepdhaka** [MichaelVoelkel/qt-collapsible-section#1]
Place LGPL header with Author name and email.
see: https://stackoverflow.com/questions/32476006/how-to-make-an-expandable-collapsable-section-widget-in-qt#comment73425868_37119983

**Comment by MichaelVoelkel** [comment]
Should be clarified now, thank you!

**Comment by kuldeepdhaka** [comment]
@Elypson "Foobar is free software" :p  
https://github.com/Elypson/qt-collapsible-section/blob/master/Section.cpp#L7

**Comment by MichaelVoelkel** [comment]
oops, thanks :)
