### ISSUE TITLE
Use toggled signal instead of clicked to allow in-code expansion/collapse

### ISSUE THREAD

**Issue by ricekab** [MichaelVoelkel/qt-collapsible-section#2]
Instead of using the `clicked` signal it would be handier to use the `toggled` signal on line 65 (https://github.com/Elypson/qt-collapsible-section/blob/master/Section.cpp#L65). Using `toggled` will allow the content to respond to the checked state changing externally. 

My particular use case was that I wanted to be able to expand all / collapse all easily.

**Comment by MichaelVoelkel** [comment]
Good idea! I have changed it
