### ISSUE TITLE
Dynamically changing widgets in collapsible error.

### ISSUE THREAD

**Issue by apalomer** [MichaelVoelkel/qt-collapsible-section#3]
Hi,

First of all, thank you for such a nice contribution. I've started to try your widget and it is impressive. However, when the content of the collapsible area is changed strange things happen. I've [forked your repo](https://github.com/apalomer/qt-collapsible-section) and modified the main application to show this issues in two different commits:

- The [first commit](https://github.com/apalomer/qt-collapsible-section/commit/dd83781c5b06488f728b927db0d4080531c0cd3f) a new label is added to the collapsible are every time the selected text of the list is changed. The new labels keep appearing but the size of the  collapsible area is never recomputed. This makes the widgets within the collapsible are useless as they cannot be displayed properly.

- I though I could fix this by resetting the entire layout every time I add a new widget to it, to make sure that the animations are set properly. The [second commit](https://github.com/apalomer/qt-collapsible-section/commit/5b9b9f721bf9dac1fc7fed0d313404bd21bcc307) implements this. However, in this case no widget is displayed at all. In this case, it lloks like the problem might be in `auto contentHeight = contentLayout.sizeHint().height();` as it does not provide a reasonable size (it provides 0), although the inner widgets are default qt widgets (in the example case a QLabel) with the appropriate `sizeHint`.

I have tried to solve this issue without any sucess. Any ideas on how to solve it?

**Comment by MichaelVoelkel** [comment]
Hi,

sorry for the late answer.

Yeah, it's tricky. The original collapsed size is nice but the content size changes. So, what I did is offer a function that actually updates the animations AND the size (if not collapsed). So using that, you can just call `updateHeights` if any content has changed. You need to do it dynamically for now, but that gives some control over it, I guess.

Maybe, could you test it first? https://github.com/MichaelVoelkel/qt-collapsible-section/pull/7

**Comment by MichaelVoelkel** [comment]
Ok, merged it regardless because more might profit than suffer from it.
